### ISSUE TITLE
Questions About Active Learning

### ISSUE THREAD

**Issue by oneChuuforya** [shendu-ht/SLA-VAE#3]
Thanks for the great work, but isn't there an active learning part of this code?

**Comment by shendu-ht** [comment]
The active learning part aims to learn and update the online model from a small amount of highly uncertain samples. In practice, this process can be understood as retraining the model based on online uncertain feedback data. The model outputs contain the uncertainty. Based on it, we can select target uncertain sample. This logic is easy to be accomplished so that we did not provide a sample selection method for active learning.

**Comment by oneChuuforya** [comment]
Ok, thanks for the reply
